/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/auth/login': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['AuthController_login']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/auth/refresh': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['AuthController_refreshToken']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/auth/logout': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['AuthController_logout']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/auth/logout-all': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['AuthController_logoutAll']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/currentUser': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['AuthController_currentUser']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/me': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['AuthController_getProfile']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/admin/register': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: operations['AdminController_add']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/version': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['VersionController_getProfile']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/tracking': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['VersionController_tracking']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/span': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['VersionController_span']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取监控事件列表 */
        get: operations['EventsController_getEvents']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取事件详情 */
        get: operations['EventsController_getEventById']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/sourcemap/status': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 批量查询 SourceMap 解析状态 */
        get: operations['EventsController_getSourceMapStatuses']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stats/summary': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取监控统计数据 */
        get: operations['EventsController_getStats']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/app/{appId}/summary': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取应用事件摘要 */
        get: operations['EventsController_getAppSummary']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/sessions/list': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取会话列表 */
        get: operations['EventsController_getSessions']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/sessions/stats': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取会话统计数据 */
        get: operations['EventsController_getSessionStats']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/sessions/{sessionId}/replay': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取会话回放数据 */
        get: operations['EventsController_getSessionReplay']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/sessions/{sessionId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 按会话ID查询事件 */
        get: operations['EventsController_getEventsBySession']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/performance/slow-requests': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取慢请求列表 */
        get: operations['EventsController_getSlowRequests']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/errors/groups': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取错误聚合（按指纹分组） */
        get: operations['EventsController_getErrorGroups']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/users/{userId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 按用户查询事件 */
        get: operations['EventsController_getUserEvents']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stats/sampling': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取采样率统计 */
        get: operations['EventsController_getSamplingStats']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/events': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 通用事件流（SSE） */
        get: operations['EventsStreamController_streamEvents']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/errors': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 错误事件流（SSE） */
        get: operations['EventsStreamController_streamErrors']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/performance': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 性能事件流（SSE） */
        get: operations['EventsStreamController_streamPerformance']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/web-vitals': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Web Vitals 实时指标（SSE） */
        get: operations['EventsStreamController_streamWebVitals']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/stats': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 实时统计数据（SSE） */
        get: operations['EventsStreamController_streamStats']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/events/stream/sourcemap-progress': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** SourceMap 解析进度（SSE） */
        get: operations['EventsStreamController_streamSourceMapProgress']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/application': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: operations['ApplicationController_list']
        put: operations['ApplicationController_update']
        post: operations['ApplicationController_create']
        delete: operations['ApplicationController_delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/smart-groups': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 智能错误聚合 */
        get: operations['ErrorAnalyticsController_getSmartErrorGroups']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/trends': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取错误趋势分析 */
        get: operations['ErrorAnalyticsController_getErrorTrends']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/trends/compare': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 对比多个错误的趋势 */
        get: operations['ErrorAnalyticsController_compareErrorTrends']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/spike-detection': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 检测错误突增 */
        get: operations['ErrorAnalyticsController_detectErrorSpikes']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/recent-spikes': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取最近的错误突增告警 */
        get: operations['ErrorAnalyticsController_getRecentSpikes']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/stream/spikes': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 错误突增告警实时推送（SSE） */
        get: operations['ErrorAnalyticsStreamController_streamErrorSpikes']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/error-analytics/stream/trends': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 错误趋势实时更新（SSE） */
        get: operations['ErrorAnalyticsStreamController_streamErrorTrends']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/health': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 系统完整健康检查 */
        get: operations['HealthController_health']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/health/ping': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 快速健康检查 */
        get: operations['HealthController_ping']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/health/dependencies': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 检查所有依赖服务状态 */
        get: operations['HealthController_dependencies']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/sourcemaps/upload': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Upload source map file */
        post: operations['SourceMapController_upload']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/alerts/rules': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取告警规则列表 */
        get: operations['AlertsController_getRules']
        put?: never
        /** 创建告警规则 */
        post: operations['AlertsController_createRule']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/alerts/rules/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取告警规则详情 */
        get: operations['AlertsController_getRuleById']
        /** 更新告警规则 */
        put: operations['AlertsController_updateRule']
        post?: never
        /** 删除告警规则 */
        delete: operations['AlertsController_deleteRule']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/alerts/history': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** 获取告警历史 */
        get: operations['AlertsController_getHistory']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        CreateAlertRuleDto: {
            /** @description 应用ID */
            app_id: string
            /** @description 规则名称 */
            name: string
            /**
             * @description 告警类型
             * @enum {string}
             */
            type: 'error_rate' | 'slow_request' | 'session_anomaly'
            /** @description 阈值 */
            threshold: number
            /**
             * @description 时间窗口
             * @example 5m
             */
            window: string
            /** @description 是否启用 */
            enabled?: boolean
            /** @description 通知渠道 */
            notification_channels?: string[]
        }
        UpdateAlertRuleDto: {
            /** @description 规则名称 */
            name?: string
            /** @description 阈值 */
            threshold?: number
            /** @description 时间窗口 */
            window?: string
            /** @description 是否启用 */
            enabled?: boolean
            /** @description 通知渠道 */
            notification_channels?: string[]
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AuthController_refreshToken: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AuthController_logout: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AuthController_logoutAll: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AuthController_currentUser: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AuthController_getProfile: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AdminController_add: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    VersionController_getProfile: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    VersionController_tracking: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    VersionController_span: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getEvents: {
        parameters: {
            query: {
                appId?: string
                eventType?: string
                limit?: string
                offset?: string
                startTime: string
                endTime: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getEventById: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSourceMapStatuses: {
        parameters: {
            query: {
                /** @description 事件 ID 列表（逗号分隔，最多 100 个） */
                eventIds: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getStats: {
        parameters: {
            query: {
                appId?: string
                startTime: string
                endTime: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getAppSummary: {
        parameters: {
            query?: never
            header?: never
            path: {
                appId: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSessions: {
        parameters: {
            query: {
                appId: string
                limit?: string
                offset?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSessionStats: {
        parameters: {
            query: {
                appId: string
                /** @description 时间窗口: hour, day, week，默认 day */
                timeWindow?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSessionReplay: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path: {
                sessionId: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getEventsBySession: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path: {
                sessionId: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSlowRequests: {
        parameters: {
            query: {
                appId: string
                /** @description 慢请求阈值(ms)，默认3000 */
                threshold?: string
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getErrorGroups: {
        parameters: {
            query: {
                appId: string
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getUserEvents: {
        parameters: {
            query: {
                appId: string
                limit?: string
            }
            header?: never
            path: {
                userId: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsController_getSamplingStats: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamEvents: {
        parameters: {
            query: {
                appId: string
                type?: 'error' | 'performance' | 'webVital' | 'message' | 'transaction' | 'custom'
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamErrors: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamPerformance: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamWebVitals: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamStats: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    EventsStreamController_streamSourceMapProgress: {
        parameters: {
            query: {
                eventId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ApplicationController_list: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ApplicationController_update: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ApplicationController_create: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ApplicationController_delete: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsController_getSmartErrorGroups: {
        parameters: {
            query: {
                appId: string
                /** @description 相似度阈值（0-1），默认 0.8 */
                threshold?: string
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsController_getErrorTrends: {
        parameters: {
            query: {
                appId: string
                /** @description 错误指纹，不提供则统计所有错误 */
                fingerprint?: string
                /** @description 时间窗口粒度 */
                window: 'hour' | 'day' | 'week'
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsController_compareErrorTrends: {
        parameters: {
            query: {
                appId: string
                /** @description 错误指纹数组，逗号分隔，最多10个 */
                fingerprints: string
                window: 'hour' | 'day' | 'week'
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsController_detectErrorSpikes: {
        parameters: {
            query: {
                appId: string
                /** @description 时间窗口，默认 hour */
                window?: 'hour' | 'day'
                /** @description 回看窗口数量，默认 24 */
                lookback?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsController_getRecentSpikes: {
        parameters: {
            query: {
                appId: string
                /** @description 最大返回数量，默认 10 */
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsStreamController_streamErrorSpikes: {
        parameters: {
            query: {
                appId: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    ErrorAnalyticsStreamController_streamErrorTrends: {
        parameters: {
            query: {
                appId: string
                fingerprint?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    HealthController_health: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    HealthController_ping: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    HealthController_dependencies: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    SourceMapController_upload: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_getRules: {
        parameters: {
            query?: {
                appId?: string
                type?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_createRule: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateAlertRuleDto']
            }
        }
        responses: {
            201: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_getRuleById: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_updateRule: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: string
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['UpdateAlertRuleDto']
            }
        }
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_deleteRule: {
        parameters: {
            query?: never
            header?: never
            path: {
                id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    AlertsController_getHistory: {
        parameters: {
            query?: {
                appId?: string
                ruleId?: string
                limit?: string
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            200: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
